### ISSUE TITLE
Put image files as assets in the repository

### ISSUE THREAD

**Issue by pReya** [orcular-org/Basislernmodule-Fab-Labs#1]
Currently, all image files are associated with the GitHub user, and they are not part of the repository (you can't find any of the image files in the actual file explorer, and their link starts with `https://user-images.githubusercontent.com...`)

This is problematic, because if the user account gets deleted, banned, etc. these images won't be available anymore – even though the rest of the content will still be available.

The images should be colocated together with the actual markdown files (either "flat" or by creating a "images" folder inside of the individual lessons).

**Comment by orcular-org** [comment]
Done! Images have been uploaded to "images" folders and image paths in the md-files have been updated.
