### ISSUE TITLE
Add explicit license file

### ISSUE THREAD

**Issue by pReya** [orcular-org/Basislernmodule-Fab-Labs#2]
For GitHub metadata to correctly pick up the license of this content, it would be nice to have an explicit `LICENSE` file at the top level of the repository. GitHub also has templates for all popular licenses, so you don't need to copy it yourself. Just create the new file in the Web UI and it will present a choice of popular licenses.

**Comment by orcular-org** [comment]
Done! Copied license file for CC-BY-SA from https://github.com/santisoler/cc-licenses/ .
