### ISSUE TITLE
Remove empty readme.md files

### ISSUE THREAD

**Issue by pReya** [orcular-org/Basislernmodule-Fab-Labs#3]
In the content folder are mutliple empty `readme.md` files, which can probably be removed:

https://github.com/orcular-org/Basislernmodule-Fab-Labs/blob/main/Basislernmodule/readme.md
https://github.com/orcular-org/Basislernmodule-Fab-Labs/blob/main/Basislernmodule/1.1%203D-Design/readme.md
https://github.com/orcular-org/Basislernmodule-Fab-Labs/blob/main/Basislernmodule/1.2%203D-Scanning/readme.md
https://github.com/orcular-org/Basislernmodule-Fab-Labs/blob/main/Basislernmodule/1.3%20Verwendung%20von%203D%20Modellen%20aus%20dem%20Internet/readme.md
https://github.com/orcular-org/Basislernmodule-Fab-Labs/blob/main/Basislernmodule/2.1%203D-Druck/readme.md
https://github.com/orcular-org/Basislernmodule-Fab-Labs/blob/main/Basislernmodule/2.2%20Lasercutting/readme.md
https://github.com/orcular-org/Basislernmodule-Fab-Labs/blob/main/Basislernmodule/2.3%20CNC-Fr%C3%A4sen/readme.md

**Comment by orcular-org** [comment]
Done!
